
####################################################################################
# Generated by Vivado 2017.4 built on 'Fri Dec 15 20:55:39 MST 2017' by 'xbuild'
# Command Used: write_xdc -force CombinationLock.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
